name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 트리거

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519  # 올바른 권한 설정
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to Public Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/seungjae-yu/photo-rating-app.git public
          rm -rf public/*
          cp -r build/* public/
          cd public
          git add .
          git commit -m "Deploy site"
          git push origin gh-pages --force
